### ISSUE TITLE
Error in setting up FCM Key, Push notification

### ISSUE THREAD

**Issue by MaliahRajan** [Countly/countly-server#1153]
API Error log : 

Unhandled rejection for {} with reason {} stack  Error: Couldn't find job file named push:validate
    at Handle.runTransient (/var/www/html/countly/api/parts/jobs/handle.js:91:19)
    at Promise.all.results.map.mongo (/var/www/html/countly/plugins/push/api/parts/endpoints.js:1356:37)
    at Array.map (<anonymous>)
    at Promise.all.then.results (/var/www/html/countly/plugins/push/api/parts/endpoints.js:1352:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2020-01-30T12:16:33.833Z: ERROR [core:api] Logging unhandled rejection
Trace
    at process.on (/var/www/html/countly/api/api.js:173:13)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by ar2rsawseen** [comment]
Hello
it would mean that file `countly/plugins/push/api/jobs/validate.js` is missing or there is no permission to open it, or maybe open file limit reached?

**Comment by MaliahRajan** [comment]
Problem is with apn ( https://github.com/Countly/countly-server/tree/master/plugins/push/api/parts/apn
 ) build - node-gyp rebuild, 

Flow  : While trying to validate Android FCM key.

Error :  nghttp2_session_want_write can not be used when making a shared object

Platform : Ubuntu 18.04 64bit 

Any fix for this ?

**Comment by iartem** [comment]
I guess the installation didn't go well. Can you rerun it?

**Comment by iartem** [comment]
Closing because of no activity
