### ISSUE TITLE
no mongos proxy available  countly-frontend

### ISSUE THREAD

**Issue by zyriuse75** [Countly/countly-server#1267]
Hi 
I trying to install countly on kubernetes.  however when  i creating the **countly-frontend pod** , I get the error below and I would like to know if the web **plugin** **needs** to connect to the **internet** when **creating** the **pod**?

```
Installing web plugin
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-07T09:55:09.050Z: ERROR	[db:read]	Error reading apps {"name":"find","args":[{}]} MongoError: no mongos proxy available {"name":"MongoError"}
```

**Comment by ar2rsawseen** [comment]
from your error, it seems it needs to connect to database :)

**Comment by zyriuse75** [comment]
i will must have this issue for all installing plugin ?  however not  only for few plugin ( alerts , compliance-hub, assistant, ratings, crash, systemlogs logger , views ,web )

```

docker] Using COUNTLY_PLUGINS: mobile,web,desktop,density,locale,browser,sources,views,enterpriseinfo,logger,systemlogs,errorlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,assistant,plugin-upload,times-of-day,compliance-hub,video-intelligence-monetization,alerts,onboarding
[docker] Installing mobile:
[docker] Done installing mobile.
[docker] Installing web:
Installing web plugin
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
No apps to upgrade
2020-04-08T18:46:03.548Z: ERROR	[db:read]	Error reading apps {"name":"find","args":[{}]} MongoError: no mongos proxy available {"name":"MongoError"}
[docker] Done installing web.
[docker] Installing desktop:
[docker] Done installing desktop.
[docker] Installing density:
[docker] Done installing density.
[docker] Installing locale:
[docker] Done installing locale.
[docker] Installing browser:
[docker] Done installing browser.
[docker] Installing sources:
[docker] Done installing sources.
[docker] Installing views:
Installing views plugin
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-08T18:46:22.051Z: ERROR	[db:read]	Error reading apps {"name":"find","args":[{}]} MongoError: no mongos proxy available {"name":"MongoError"}
[docker] Done installing views.
[docker] Installing enterpriseinfo:
[docker] Done installing enterpriseinfo.
[docker] Installing logger:
Installing logger plugin
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-08T18:46:36.852Z: ERROR	[db:read]	Error reading apps {"name":"find","args":[{}]} MongoError: no mongos proxy available {"name":"MongoError"}
[docker] Done installing logger.
[docker] Installing systemlogs:
Installing systemlogs plugin
Adding systemlogs indexes
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-08T18:46:50.750Z: ERROR	[db:read]	Error reading systemlogs {"name":"findOne","args":[{"_id":"meta_v2"},null]} MongoError: no mongos proxy available {"name":"MongoError"}
2020-04-08T18:47:00.849Z: ERROR	[db:write]	Error writing systemlogs {"name":"updateOne","args":[{"_id":"meta_v2"},{"$unset":{"a":1}},null]} MongoError: no mongos proxy available {"name":"MongoError"}
Systemlogs plugin installation finished
[docker] Done installing systemlogs.
[docker] Installing errorlogs:
[docker] Done installing errorlogs.
[docker] Installing populator:
[docker] Done installing populator.
[docker] Installing reports:
[docker] Done installing reports.
[docker] Installing crashes:
Installing crash plugin
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-08T18:47:27.053Z: ERROR	[db:read]	Error reading apps {"name":"find","args":[{}]} MongoError: no mongos proxy available {"name":"MongoError"}
[docker] Done installing crashes.
[docker] Installing push:
[docker] Done installing push.
[docker] Installing star-rating:
Installing ratings plugin
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-08T18:47:41.750Z: ERROR	[db:read]	Error reading apps {"name":"find","args":[{}]} MongoError: no mongos proxy available {"name":"MongoError"}
[docker] Done installing star-rating.
[docker] Installing slipping-away-users:
[docker] Done installing slipping-away-users.
[docker] Installing compare:
[docker] Done installing compare.
[docker] Installing server-stats:
[docker] Done installing server-stats.
[docker] Installing dbviewer:
[docker] Done installing dbviewer.
[docker] Installing assistant:
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
[docker] Done installing assistant.
[docker] Installing plugin-upload:
[docker] Done installing plugin-upload.
[docker] Installing times-of-day:
[docker] Done installing times-of-day.
[docker] Installing compliance-hub:
Installing compliance-hub plugin
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-08T18:48:24.450Z: ERROR	[db:read]	Error reading apps {"name":"find","args":[{}]} MongoError: no mongos proxy available {"name":"MongoError"}
No apps to upgrade
[docker] Done installing compliance-hub.
[docker] Installing video-intelligence-monetization:
[docker] Done installing video-intelligence-monetization.
[docker] Installing alerts:
Installing alerts plugin
Adding alerts patch
{ MongoError: no mongos proxy available
    at Timeout.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/mongos.js:736:28)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'MongoError', [Symbol(mongoErrorContextSymbol)]: {} }
2020-04-08T18:48:39.047Z: ERROR	[db:write]	Error writing alerts {"name":"updateMany","args":[{"period":"every 10 seconds"},{"$set":{"period":"every 59 mins starting on the 59 min"}},{"upsert":false,"multi":true},null]} MongoError: no mongos proxy available {"name":"MongoError"}
Alerts plugin installation finished
[docker] Done installing alerts.
[docker] Installing onboarding:
[docker] Done installing onboarding.
Running "concat:dom" (concat) task

Running "concat:utils" (concat) task

Running "concat:visualization" (concat) task

Running "concat:lib" (concat) task

Running "uglify:dist" (uglify) task
```

**Comment by iartem** [comment]
@zyriuse75 your container doesn't have a db connection. We have a detailed guide [here](https://support.count.ly/hc/en-us/articles/360037814511-Docker-Kubernetes).

Next time please use Slack or community forums for support.
