### ISSUE TITLE
error-log

### ISSUE THREAD

**Issue by shenyubao** [Countly/countly-server#138]
log/countly-dashboard.log
---------------------------
Error: Forbidden
    at Object.exports.error (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/utils.js:60:13)
    at Object.handle (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/middleware/csrf.js:54:41)
    at next (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle] (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)
    at next (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.handle (/alidata1/souche/countly-server/trunk/frontend/express/app.js:112:9)
    at next (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.handle (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/connect-flash/lib/flash.js:21:5)
    at next (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.session [as handle] (/alidata1/souche/countly-server/trunk/frontend/express/node_modules/express/node_modules/connect/lib/middleware/session.js:302:7)

**Comment by ar2rsawseen** [comment]
It would basically mean that a POST request was sent to a server without proper CSRF value that server expected.

Can you elaborate on which scenario did you achieve this error?

**Comment by ar2rsawseen** [comment]
I've reproduced the issue with multiple instances of countly opened in separate tabs.
In this case server generates multiple csrf. but only the last one generated is a valid. Thus you get such error.

Similar thing happens in tests with multiple paraler requests
