### ISSUE TITLE
Failed to install Countly server using one liner installation

### ISSUE THREAD

**Issue by JasonLCY3** [Countly/countly-server#1684]
### Expected Behavior

Successfully install Countly server.

### Current Behavior

Throw an error which stops the installation
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn nodejs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn nodejs',
  path: 'nodejs',
  spawnargs: [ '/root/countly/plugins/mobile/install.js' ]
}
```

### Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/24191781/101980810-197eac80-3ca3-11eb-9e04-556a3e977be2.png)

### Steps to Reproduce (for bugs)

1. Run `wget -qO- https://c.ly/install | bash` on Ubuntu Server 20.04.1

### Your Environment

* Operating System and version: Ubuntu Server 20.04.1
* Any changes you have made to your instance:

**Comment by ar2rsawseen** [comment]
Hello,
the latest release did not support Ubuntu 20, but it has been fixed in the repo and will be released in the minor release next week :)
