### ISSUE TITLE
Error trying to update events overview on Firefox

### ISSUE THREAD

**Issue by backmeupplz** [Countly/countly-server#1783]
### Expected Behavior
New events overview should be saved

### Current Behavior
An error appears

### Screenshots
![Screen Shot 2021-03-31 at 7 05 34 AM](https://user-images.githubusercontent.com/3192028/113157749-07902d80-91f0-11eb-9f52-07711534294e.png)

### Possible Solution
Probably a frontend bug?

### Steps to Reproduce (for bugs)
1. Open Countly Community edition
2. Try to modify events overview

### Your Environment

* Operating System and version: macOS 11.2.3
* Countly v20.11.1
* This only happens on Firefox, Chrome is fine

**Comment by backmeupplz** [comment]
```Caught exception: {} TypeError: Cannot read property 'uid' of undefined
    at /usr/local/countly/plugins/enterpriseinfo/frontend/app.js:66:108
    at /usr/local/countly/plugins/pluginManager.js:1523:29
    at executeCallback (/usr/local/countly/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
    at handleCallback (/usr/local/countly/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.next (/usr/local/countly/node_modules/mongodb/lib/operations/find_one.js:29:9)
    at /usr/local/countly/node_modules/mongodb/lib/utils.js:731:5
    at cursor._next (/usr/local/countly/node_modules/mongodb/lib/cursor.js:251:9)
    at handleCallback (/usr/local/countly/node_modules/mongodb/lib/core/cursor.js:32:5)
    at nextFunction (/usr/local/countly/node_modules/mongodb/lib/core/cursor.js:870:5)
    at self._initializeCursor (/usr/local/countly/node_modules/mongodb/lib/core/cursor.js:745:7)
    at done (/usr/local/countly/node_modules/mongodb/lib/core/cursor.js:454:7)
    at queryCallback (/usr/local/countly/node_modules/mongodb/lib/core/cursor.js:500:18)
    at executeOperation (/usr/local/countly/node_modules/mongodb/lib/core/cursor.js:550:9)
    at executeCallback (/usr/local/countly/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
    at callbackWithRetry (/usr/local/countly/node_modules/mongodb/lib/operations/execute_operation.js:118:14)
    at fn (/usr/local/countly/node_modules/mongodb/lib/cmap/connection_pool.js:352:13)
2021-03-13T09:36:42.614Z: ERROR	[core:app]	Logging caught exception
```

Error log

**Comment by ar2rsawseen** [comment]
Hello
error message indeed seems to come from backend, but the error you shared should not have anything to do with this case.

But of course, as usually, I cannot reproduce this :D 

Were there any errors in countly-api.log?

Also as far as I see you only tried to add event that is in screenshot? so no weird symbols were involved, only underscore as one of the special symbols, right?

**Comment by backmeupplz** [comment]
@ar2rsawseen yep, I downloaded Countly log from the backend :) No weird symbols involved, works well in Chrome, doesn't work in Firefox for any of the event and/or properties (e.g. `count`, `sum`).

Actually, just looked into the network log, it is getting blocked by U Block extension :D sorry for the troubles. Turning off uBlock solved the issue :) I don't have uBlock installed on Chrome, that's why it worked.

![Screen Shot 2021-03-31 at 8 41 57 AM](https://user-images.githubusercontent.com/3192028/113172346-34970d00-91fd-11eb-9600-af12d4e3c831.png)

**Comment by ar2rsawseen** [comment]
No problem, glad it is resolved :)
