### ISSUE TITLE
Running clountly on GKE - Not able to add application

### ISSUE THREAD

**Issue by success4us** [Countly/countly-server#1888]
I am trying to countly on GKE. I followed the steps from this document https://support.count.ly/hc/en-us/articles/360037814511#setting-up-a-kubernetes-cluster. once all the deployments are running then I'm able to login to the countly but when I fill add application page it's not responding. I have configured ingress with an external URL and tls cert, also configured frontend and backend COUNTLY_CONFIG_HOSTNAME env with the external URL.

### Expected Behavior

To add a web application for analytics

### Current Behavior

**These are the logs from the frontend pod**

Error: Cannot find module './errorlogs/frontend/app'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at pluginManager.loadAppStatic (/opt/countly/plugins/pluginManager.js:507:30)
    at Object.<anonymous> (/opt/countly/frontend/express/app.js:415:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error: Cannot find module './plugin-upload/frontend/app'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at pluginManager.loadAppStatic (/opt/countly/plugins/pluginManager.js:507:30)
    at Object.<anonymous> (/opt/countly/frontend/express/app.js:415:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error while reading folder of plugin errorlogs: "Error: ENOENT: no such file or directory, scandir '/opt/countly/frontend/express/../../plugins/errorlogs/frontend/public/javascripts'\n    at Object.readdirSync (fs.js:790:3)\n    at plgns.forEach.plugin (/opt/countly/frontend/express/app.js:905:35)\n    at Array.forEach (<anonymous>)\n    at /opt/countly/frontend/express/app.js:903:15\n    at Function.app.loadThemeFiles (/opt/countly/frontend/express/app.js:349:13)\n    at renderDashboard (/opt/countly/frontend/express/app.js:807:9)\n    at /opt/countly/frontend/express/app.js:949:25\n    at /opt/countly/plugins/pluginManager.js:1529:29\n    at /opt/countly/node_modules/mongodb/lib/utils.js:731:5\n    at handleCallback (/opt/countly/node_modules/mongodb/lib/utils.js:128:55)\n    at cursor.close (/opt/countly/node_modules/mongodb/lib/cursor.js:841:66)\n    at handleCallback (/opt/countly/node_modules/mongodb/lib/utils.js:128:55)\n    at completeClose (/opt/countly/node_modules/mongodb/lib/cursor.js:929:16)\n    at Cursor.close (/opt/countly/node_modules/mongodb/lib/cursor.js:948:12)\n    at cursor._next (/opt/countly/node_modules/mongodb/lib/cursor.js:841:27)\n    at self._initializeCursor (/opt/countly/node_modules/mongodb/lib/core/cursor.js:741:9)"
Error while reading folder of plugin plugin-upload: "Error: ENOENT: no such file or directory, scandir '/opt/countly/frontend/express/../../plugins/plugin-upload/frontend/public/javascripts'\n    at Object.readdirSync (fs.js:790:3)\n    at plgns.forEach.plugin (/opt/countly/frontend/express/app.js:905:35)\n    at Array.forEach (<anonymous>)\n    at /opt/countly/frontend/express/app.js:903:15\n    at Function.app.loadThemeFiles (/opt/countly/frontend/express/app.js:349:13)\n    at renderDashboard (/opt/countly/frontend/express/app.js:807:9)\n    at /opt/countly/frontend/express/app.js:949:25\n    at /opt/countly/plugins/pluginManager.js:1529:29\n    at /opt/countly/node_modules/mongodb/lib/utils.js:731:5\n    at handleCallback (/opt/countly/node_modules/mongodb/lib/utils.js:128:55)\n    at cursor.close (/opt/countly/node_modules/mongodb/lib/cursor.js:841:66)\n    at handleCallback (/opt/countly/node_modules/mongodb/lib/utils.js:128:55)\n    at completeClose (/opt/countly/node_modules/mongodb/lib/cursor.js:929:16)\n    at Cursor.close (/opt/countly/node_modules/mongodb/lib/cursor.js:948:12)\n    at cursor._next (/opt/countly/node_modules/mongodb/lib/cursor.js:841:27)\n    at self._initializeCursor (/opt/countly/node_modules/mongodb/lib/core/cursor.js:741:9)"

**These are the logs from the api pod**

Error: Cannot find module './errorlogs/api/api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at pluginManager.init (/opt/countly/plugins/pluginManager.js:66:43)
    at Object.<anonymous> (/opt/countly/api/api.js:112:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error: Cannot find module './plugin-upload/api/api'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at pluginManager.init (/opt/countly/plugins/pluginManager.js:66:43)
    at Object.<anonymous> (/opt/countly/api/api.js:112:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Starting worker 315 parent: 6
Starting worker 301 parent: 6
2021-06-16T05:52:11.239Z: INFO	[jobs:job]	Replacing jobs reports:send ({"status":0,"name":"reports:send"})
2021-06-16T05:52:11.243Z: INFO	[jobs:job]	Replacing jobs server-stats:stats ({"status":0,"name":"server-stats:stats"})
2021-06-16T05:52:11.244Z: INFO	[jobs:job]	Replacing jobs api:topEvents ({"status":0,"name":"api:topEvents"})
2021-06-16T05:52:11.245Z: INFO	[jobs:job]	Replacing jobs api:ping ({"status":0,"name":"api:ping"})
2021-06-16T05:52:11.245Z: INFO	[jobs:job]	Replacing jobs api:clear ({"status":0,"name":"api:clear"})
2021-06-16T05:52:11.246Z: INFO	[jobs:job]	Replacing jobs api:clearTokens ({"status":0,"name":"api:clearTokens"})
2021-06-16T05:52:11.247Z: INFO	[jobs:job]	Replacing jobs api:clearAutoTasks ({"status":0,"name":"api:clearAutoTasks"})
2021-06-16T05:52:11.249Z: INFO	[jobs:job]	Replacing jobs api:task ({"status":0,"name":"api:task"})
2021-06-16T05:52:11.250Z: INFO	[jobs:job]	Replacing jobs api:userMerge ({"status":0,"name":"api:userMerge"})
2021-06-16T05:52:11.252Z: INFO	[jobs:job]	Cancelled 1 previous jobs reports:send ({"status":0,"name":"reports:send"})
2021-06-16T05:52:11.253Z: INFO	[jobs:job]	Cancelled 1 previous jobs server-stats:stats ({"status":0,"name":"server-stats:stats"})
2021-06-16T05:52:11.254Z: INFO	[jobs:job]	Cancelled 1 previous jobs api:topEvents ({"status":0,"name":"api:topEvents"})
2021-06-16T05:52:11.255Z: INFO	[jobs:job]	Cancelled 1 previous jobs api:ping ({"status":0,"name":"api:ping"})
2021-06-16T05:52:11.256Z: INFO	[jobs:job]	Cancelled 1 previous jobs api:clear ({"status":0,"name":"api:clear"})
2021-06-16T05:52:11.257Z: INFO	[jobs:job]	Cancelled 1 previous jobs api:clearAutoTasks ({"status":0,"name":"api:clearAutoTasks"})
2021-06-16T05:52:11.258Z: INFO	[jobs:job]	Cancelled 1 previous jobs api:clearTokens ({"status":0,"name":"api:clearTokens"})
2021-06-16T05:52:11.259Z: INFO	[jobs:job]	Cancelled 1 previous jobs api:userMerge ({"status":0,"name":"api:userMerge"})
2021-06-16T05:52:11.260Z: INFO	[jobs:job]	Cancelled 1 previous jobs api:task ({"status":0,"name":"api:task"})
2021-06-16T05:52:11.261Z: INFO	[jobs:job]	No job to replace, inserting {"name":"server-stats:stats","created":1623822731242,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 day","next":1623822731242}
2021-06-16T05:52:11.263Z: INFO	[jobs:job]	No job to replace, inserting {"name":"reports:send","created":1623822731235,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 hour starting on the 0 min","next":1623822731238}
2021-06-16T05:52:11.263Z: INFO	[jobs:job]	No job to replace, inserting {"name":"api:ping","created":1623822731244,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 day","next":1623822731245}
2021-06-16T05:52:11.264Z: INFO	[jobs:job]	No job to replace, inserting {"name":"api:topEvents","created":1623822731243,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 day","next":1623822731244}
2021-06-16T05:52:11.265Z: INFO	[jobs:job]	No job to replace, inserting {"name":"api:clearAutoTasks","created":1623822731247,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 day","next":1623822731247}
2021-06-16T05:52:11.266Z: INFO	[jobs:job]	No job to replace, inserting {"name":"api:clear","created":1623822731245,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 day","next":1623822731245}
2021-06-16T05:52:11.267Z: INFO	[jobs:job]	No job to replace, inserting {"name":"api:userMerge","created":1623822731249,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 hour on the 10th min","next":1623823800000}
2021-06-16T05:52:11.268Z: INFO	[jobs:job]	No job to replace, inserting {"name":"api:clearTokens","created":1623822731246,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 1 day","next":1623822731246}
2021-06-16T05:52:11.270Z: INFO	[jobs:job]	No job to replace, inserting {"name":"api:task","created":1623822731248,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 5 minutes","next":1623822900000}
2021-06-16T06:00:00.321Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c991843934fa00063621e0","name":"assistant:generate","created":1623822724238,"status":0,"started":null,"finished":null,"duration":0,"data":{},"schedule":"every 30 minutes starting on the 0 min","next":1623823200000}
2021-06-16T06:00:00.386Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e2","name":"reports:send","created":1623822731235,"status":0,"started":1623822731519,"finished":1623822731530,"duration":15,"data":{},"schedule":"every 1 hour starting on the 0 min","next":1623823200000,"modified":1623822731534,"error":null}
2021-06-16T06:00:00.390Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623822900023,"finished":1623822900028,"duration":7,"data":{},"schedule":"every 5 minutes","next":1623823200000,"modified":1623822900030,"error":null}
2021-06-16T06:05:00.409Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623823200398,"finished":1623823200571,"duration":176,"data":{},"schedule":"every 5 minutes","next":1623823500000,"modified":1623823200574,"error":null}
2021-06-16T06:15:00.259Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623823800227,"finished":1623823800234,"duration":9,"data":{},"schedule":"every 5 minutes","next":1623824100000,"modified":1623823800236,"error":null}
2021-06-16T06:20:00.204Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623824100262,"finished":1623824100266,"duration":6,"data":{},"schedule":"every 5 minutes","next":1623824400000,"modified":1623824100268,"error":null}
2021-06-16T06:25:00.089Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623824400206,"finished":1623824400212,"duration":8,"data":{},"schedule":"every 5 minutes","next":1623824700000,"modified":1623824400214,"error":null}
2021-06-16T06:45:00.473Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623825600338,"finished":1623825600341,"duration":4,"data":{},"schedule":"every 5 minutes","next":1623825900000,"modified":1623825600342,"error":null}
2021-06-16T06:50:00.258Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623825900476,"finished":1623825900480,"duration":6,"data":{},"schedule":"every 5 minutes","next":1623826200000,"modified":1623825900482,"error":null}
2021-06-16T06:55:00.108Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623826200260,"finished":1623826200266,"duration":8,"data":{},"schedule":"every 5 minutes","next":1623826500000,"modified":1623826200268,"error":null}
2021-06-16T07:15:00.372Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623827400188,"finished":1623827400194,"duration":8,"data":{},"schedule":"every 5 minutes","next":1623827700000,"modified":1623827400196,"error":null}
2021-06-16T07:20:00.209Z: INFO	[jobs:manager]	Trying to start job {"_id":"60c9918b3934fa00063621e9","name":"api:task","created":1623822731248,"status":0,"started":1623827700374,"finished":1623827700379,"duration":7,"data":{},"schedule":"every 5 minutes","next":1623828000000,"modified":1623827700381,"error":null}

### Your Environment

* Operating System and version: GKE - 1.17.17-gke.4900

**Comment by success4us** [comment]
Yes, I have deployed API pod from https://github.com/Countly/countly-server/tree/master/bin/docker/k8s countly-api.yaml, I have mentioned API pod's error logs also.

**Comment by success4us** [comment]
Do you know the issue?

**Comment by iartem** [comment]
Where did you get the images? Seems like your `COUNTLY_PLUGINS` has plugins disabled for docker setups.

**Comment by success4us** [comment]
The api image is: countly/api:20.04
The frontend image is: countly/frontend:20.04

I just followed your installation document https://support.count.ly/hc/en-us/articles/360037814511#setting-up-a-kubernetes-cluster. I didn't make any changes to it.

**Comment by iartem** [comment]
I don't see how it's possible. What's the value of `COUNTLY_PLUGINS` in your configs?

**Comment by success4us** [comment]
deployment.yaml file from the running api pod

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: countly-api
  name: countly-api-deployment
  namespace: countly
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: countly-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: countly-api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - countly-api
                - mongo
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: COUNTLY_PLUGINS
          value: mobile,web,desktop,plugins,density,locale,browser,sources,views,enterpriseinfo,logger,systemlogs,errorlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,assistant,plugin-upload,times-of-day,compliance-hub,video-intelligence-monetization,alerts,onboarding
        - name: COUNTLY_CONFIG_API_FILESTORAGE
          value: gridfs
        - name: COUNTLY_CONFIG__MONGODB
          value: mongodb://mongo-mongodb-replicaset-0.mongo-mongodb-replicaset:27017,mongo-mongodb-replicaset-1.mongo-mongodb-replicaset:27017,mongo-mongodb-replicaset-2.mongo-mongodb-replicaset:27017/countly?replicaSet=rs0
        - name: COUNTLY_CONFIG_HOSTNAME
          value: countly.success4.io
        image: countly/api:20.04
        imagePullPolicy: Always
        name: countly-api
        ports:
        - containerPort: 3001
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /o/ping
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources: {}

**Comment by success4us** [comment]
Hey, any update on this issue?

**Comment by iartem** [comment]
Oh sorry, yes. Please update your API & Frontend YAMLs to the latest ones in k8s folder.

**Comment by success4us** [comment]
I don't think it solved the problem. I'm still facing an issue to add the initial application. I'm attaching the console log here
![countly-console-log](https://user-images.githubusercontent.com/40060090/124722940-278a6800-df28-11eb-83a8-a331ff58805d.png)

**Comment by iartem** [comment]
This time you have some issue with the Ingress, did you also took its config from our defaults?

**Comment by success4us** [comment]
Yes, the issue is from my end. I made some ingress changes which caused this issue. I fixed it now. just a couple of questions though.
1. how to add more plugins? because in UI settings, there is no plugin UI to add plugins from UI. I can only add plugins from deployment file?
2. And I cannot see any logos even the countly logos. Is this also ingress issue?

**Comment by success4us** [comment]
Hey, Just now I wend through the document for adding custom plugins https://support.count.ly/hc/en-us/articles/360037814511-Docker-and-Kubernetes#adding-custom-plugins

I just don't understand this part.

"**COPY plugins/YOUR_PLUGIN /opt/countly/plugins/YOUR_PLUGIN**"

do I have to download the plugin and then add it to the docker image or what is that folder?

**Comment by iartem** [comment]
Hi,
0. Yes, no images must be an ingress issue, assuming it's not about app icons (see below).
1. Yep, you found the link. Our Community Edition docker images contain all the CE plugins supported. Unless you have a custom plugin you'd like to put in, you shouldn't need to add anything.
2. Data migration plugin is not supported unfortunately. That's because it needs place to store data and that's generally a bad idea to store anything in a container. Plus you might have multiple containers running and we won't be able to redirect you to the right now from Nginx/Ingress.

With that being said, I'd suggest just using mongodump/mongorestore. The only catch here is images. In case you don't use gridfs for storage (check `api/config.js`), they're not stored in db. App icons can be just uploaded again, but if you have profile images, you'd need to do extra step. Let me know if that's the case.
Closing it for now as it became more of a support ticket, but feel free to comment.
