### ISSUE TITLE
frontend crash: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jianglinchun** [Countly/countly-server#213]
\frontend\express\app.js:494
                            a.api_key = md5Hash(member[0]._id + (new Date).getTime());
                                                      ^

TypeError: Cannot read property '0' of undefined
    at Request._callback (e:\code\github\jianglinchun\countly-server\frontend\express\app.js:494:55)
    at Request.self.callback (e:\code\github\jianglinchun\countly-server\node_modules\request\request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (e:\code\github\jianglinchun\countly-server\node_modules\request\request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (e:\code\github\jianglinchun\countly-server\node_modules\request\request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by jianglinchun** [comment]
fixed by update mongoskin. Sorry.
