### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by wonderful60** [Countly/countly-server#250]
Hi,I cann't add an app on http://x.x.x.x/dashboard#/manage/apps,  backend log($DIR/../log/countly-api.log) repeats a error：

`Error: Could not locate the bindings file. Tried:
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/build/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/build/Debug/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/build/Release/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/out/Debug/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/Debug/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/out/Release/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/Release/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/build/default/time.node
 → /opt/countly/node_modules/.npminstall/time/0.11.4/time/compiled/5.9.1/linux/x64/time.node
    at bindings (/opt/countly/node_modules/.npminstall/bindings/1.2.1/bindings/bindings.js:88:9)
    at Object.<anonymous> (/opt/countly/node_modules/.npminstall/time/0.11.4/time/index.js:8:35)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/countly/api/utils/common.js:3:12)
    at Module._compile (module.js:413:34)`

I am a novice, I hope someone can help me, thank you.

**Comment by wonderful60** [comment]
I know how to solve.reference：http://support.count.ly/discussions/problems/8146-installation-problem
