### ISSUE TITLE
Countly frontend:latest  crashing

### ISSUE THREAD

**Issue by repomike** [Countly/countly-server#4361]
### Current Behavior
One or more times per day the countly:frontend crashes with the following error:
```
[docker] Plugins have been built, skipping rebuilding
Starting Countly version 23.06.2 package 23.06.0
Caught exception: {} TypeError: Cannot read property 'uid' of undefined
    at /opt/countly/plugins/enterpriseinfo/frontend/app.js:53:108
    at /opt/countly/plugins/pluginManager.js:2193:25
    at /opt/countly/node_modules/mongodb/lib/utils.js:371:9
    at /opt/countly/node_modules/mongodb/lib/cursor/abstract_cursor.js:503:24
    at /opt/countly/node_modules/mongodb/lib/cursor/abstract_cursor.js:455:66
    at /opt/countly/node_modules/mongodb/lib/utils.js:371:9
    at completeEndSession (/opt/countly/node_modules/mongodb/lib/sessions.js:154:17)
    at /opt/countly/node_modules/mongodb/lib/sessions.js:166:13
    at maybePromise (/opt/countly/node_modules/mongodb/lib/utils.js:357:5)
    at ClientSession.endSession (/opt/countly/node_modules/mongodb/lib/sessions.js:133:41)
    at cleanupCursor (/opt/countly/node_modules/mongodb/lib/cursor/abstract_cursor.js:557:32)
2023-07-11T20:50:47.264Z: ERROR	[core:app]	Logging caught exception
    at /opt/countly/node_modules/mongodb/lib/cursor/abstract_cursor.js:455:24
    at /opt/countly/node_modules/mongodb/lib/cursor/find_cursor.js:66:13
    at /opt/countly/node_modules/mongodb/lib/utils.js:371:9
    at /opt/countly/node_modules/mongodb/lib/operations/execute_operation.js:73:17
    at /opt/countly/node_modules/mongodb/lib/operations/execute_operation.js:178:21
    at /opt/countly/node_modules/mongodb/lib/cmap/connection_pool.js:299:25
    at /opt/countly/node_modules/mongodb/lib/sdam/server.js:212:17
    at handleOperationResult (/opt/countly/node_modules/mongodb/lib/sdam/server.js:284:20)
    at Connection.onMessage (/opt/countly/node_modules/mongodb/lib/cmap/connection.js:219:9)
    at MessageStream.<anonymous> (/opt/countly/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (events.js:400:28)
[INFO  tini (1)] Spawned child process '/opt/countly/bin/docker/cmd.sh' with pid '7'
[INFO  tini (1)] Main child exited normally (with status '1')
```

### Expected Behavior
I would expect that the exception would be caught and handled gracefully vs. full on exit

### Your Environment

* Operating System and version:  Ubuntu 20.04.6 LTS
* Any changes you have made to your instance:  Configured SSL

**Comment by ar2rsawseen** [comment]
Hello
as far as I know enterprise-info plugin has been dropped since new UI and removed from all the docker and plugin list files.

It is possible you still have it in your COUNTLY_PLUGINS env variable for docker, can you remove it from there and try again?

**Comment by repomike** [comment]
yes we still had `enterpriseinfo` (no hyphen) in both core and api plugin list.  I removed and will restart when i can.
