### ISSUE TITLE
Cannot Add app in dashboard after the first fresh installation

### ISSUE THREAD

**Issue by mayulu** [Countly/countly-server#458]
After the first country-server install(via the community tarball), I can create the admin user. It is OK.
But after login, prompt for adding an app, I fill all the information, and click "add application" button.

Nothing happens, the app did not be added. 

###dashboard.log
```
ForbiddenError: invalid csrf token
    at csrf (/opt/countly/node_modules/csurf/index.js:112:19)
    at /opt/countly/frontend/express/app.js:355:9
    at Layer.handle [as handle_request] (/opt/countly/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/countly/node_modules/express/lib/router/index.js:317:13)
    at /opt/countly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/countly/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/countly/node_modules/express/lib/router/index.js:275:10)
    at methodOverride (/opt/countly/node_modules/method-override/index.js:79:5)
    at Layer.handle [as handle_request] (/opt/countly/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/countly/node_modules/express/lib/router/index.js:317:13)
    at /opt/countly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/countly/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/countly/node_modules/express/lib/router/index.js:275:10)
    at /opt/countly/frontend/express/app.js:346:13
    at EventEmitter.app.loadThemeFiles (/opt/countly/frontend/express/app.js:182:13)
    at /opt/countly/frontend/express/app.js:332:13

```
### Your Environment

* Operating System and version: Ubuntu 16.04
* Any changes you have made to your instance: api/config.js, frontend/express/config.js, Just modify the "localhost" to my real host. By the way, mongodb is also a fresh installation, and no auth configured.

**Comment by ar2rsawseen** [comment]
Usually that happens then there is a problem with connecting to mongodb or has a server side error.
Is there anything in countly-api.log?

**Comment by mayulu** [comment]
I think countly-api.log is normal, something like the following:
countly-api.log: 
```
2018-03-23T03:07:26.689Z: INFO	[jobs:job]	replacing job {"status":0,"name":"api:clearTokens"} with { name: 'api:clearTokens',
  created: 1521774446689,
  status: 0,
  started: null,
  finished: null,
  duration: 0,
  schedule: 'every 1 day',
  next: 1521774446689,
  modified: 1521774446689 }
2018-03-23T03:07:26.690Z: INFO	[jobs:job]	last job is scheduled correctly, won't replace anything for {"status":0,"name":"push:cleanup"}: current "2018-03-23T03:59:00.000Z", won't replace to "2018-03-23T03:59:00.000Z"
2018-03-23T03:07:26.690Z: INFO	[jobs:job]	last job is scheduled correctly, won't replace anything for {"status":0,"name":"server-stats:stats"}: current "2018-03-24T00:00:00.000Z", won't replace to "2018-03-23T03:07:26.687Z"
2018-03-23T03:07:26.691Z: INFO	[jobs:job]	last job is scheduled correctly, won't replace anything for {"status":0,"name":"api:ping"}: current "2018-03-24T00:00:00.000Z", won't replace to "2018-03-23T03:07:26.688Z"
2018-03-23T03:07:26.691Z: INFO	[jobs:job]	last job is scheduled correctly, won't replace anything for {"status":0,"name":"api:clear"}: current "2018-03-24T00:00:00.000Z", won't replace to "2018-03-23T03:07:26.688Z"
2018-03-23T03:07:26.691Z: INFO	[jobs:job]	last job is scheduled correctly, won't replace anything for {"status":0,"name":"api:clearTokens"}: current "2018-03-24T00:00:00.000Z", won't replace to "2018-03-23T03:07:26.689Z"
2018-03-23T03:30:00.146Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab46f6752b56f50e6e1354c","name":"assistant:generate","created":1521774439685,"status":0,"started":null,"finished":null,"duration":0,"schedule":"every 30 minutes starting on the 0 min","next":1521775800000,"modified":1521774439691}
2018-03-23T03:32:12.588Z: WARN	[assistantJob:module]	Assistant plugin, feed reader returned error while reading feed. url: ["https://medium.com/feed/countly"] error: [{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"66.220.158.32","port":443}]
2018-03-23T03:59:00.023Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521774000157,"finished":1521774000158,"duration":1,"schedule":"every 59 minutes","next":1521777540000,"modified":1521774000160,"error":null}
2018-03-23T04:00:00.119Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece5","name":"reports:send","created":1521740123542,"status":0,"started":1521774000157,"finished":1521774000160,"duration":3,"schedule":"every 1 hour starting on the 0 min","next":1521777600000,"modified":1521774000161,"error":null}
2018-03-23T04:00:00.120Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521777540023,"finished":1521777540025,"duration":2,"schedule":"every 59 minutes","next":1521777600000,"modified":1521777540031,"error":null}
2018-03-23T04:59:00.671Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521777600120,"finished":1521777600123,"duration":3,"schedule":"every 59 minutes","next":1521781140000,"modified":1521777600126,"error":null}
2018-03-23T05:00:00.765Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece5","name":"reports:send","created":1521740123542,"status":0,"started":1521777600120,"finished":1521777600128,"duration":8,"schedule":"every 1 hour starting on the 0 min","next":1521781200000,"modified":1521777600129,"error":null}
2018-03-23T05:00:00.765Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521781140671,"finished":1521781140672,"duration":1,"schedule":"every 59 minutes","next":1521781200000,"modified":1521781140673,"error":null}
2018-03-23T05:59:00.304Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521781200765,"finished":1521781200766,"duration":1,"schedule":"every 59 minutes","next":1521784740000,"modified":1521781200768,"error":null}
2018-03-23T06:00:00.396Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece5","name":"reports:send","created":1521740123542,"status":0,"started":1521781200765,"finished":1521781200768,"duration":3,"schedule":"every 1 hour starting on the 0 min","next":1521784800000,"modified":1521781200769,"error":null}
2018-03-23T06:00:00.397Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521784740304,"finished":1521784740305,"duration":1,"schedule":"every 59 minutes","next":1521784800000,"modified":1521784740307,"error":null}
2018-03-23T06:59:00.844Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521784800397,"finished":1521784800398,"duration":1,"schedule":"every 59 minutes","next":1521788340000,"modified":1521784800399,"error":null}
2018-03-23T07:00:00.940Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece5","name":"reports:send","created":1521740123542,"status":0,"started":1521784800396,"finished":1521784800399,"duration":3,"schedule":"every 1 hour starting on the 0 min","next":1521788400000,"modified":1521784800400,"error":null}
2018-03-23T07:00:00.940Z: INFO	[jobs:manager]	Trying to start job {"_id":"5ab3e95b099d8f1761beece6","name":"push:cleanup","created":1521740123545,"status":0,"started":1521788340845,"finished":1521788340846,"duration":1,"schedule":"every 59 minutes","next":1521788400000,"modified":1521788340847,"error":null}

```

**Comment by ar2rsawseen** [comment]
Yeah, the only interesting thing I see there is that assistant was not able to access feed, so could be that you are cut of from the internet?

I think there was an issue in 18.01 when creating first app, but not like that. But either way, rechecking, are you using latest 18.01.1?

Next thing is, maybe you can check browser console if there is any error there.

And that hostname change, also kind of bothers me, as localhost is the default internal hostname, and outside connections are managed through nginx, so it should be fine using localhost too. Can you elaborate on your hostname situation?

**Comment by mayulu** [comment]
@ar2rsawseen Yes the version is the latest.
```
 ## Version 18.01.1

```
I exposed countly server  port 6001 and 3001 directly, not behind nginx.
of course mongdb host remains "localhost"
API&Web part
```
api(web): {
        port: 3001,
        host: "my.domain",
        max_sockets: 1024,
        timeout: 120000
}
```
mongdb part
```
mongodb: {
        host: "localhost",
        db: "countly",
        port: 27017,
        max_pool_size: 500,
```

**Comment by ar2rsawseen** [comment]
Ok, any reason for doing that?
Cause that could be a problem, by default dashboard makes requests to domain/o or domain/i
Now it should make requests to domain:3001/o and domain:3001/i
So I think you need to modify this part to include domain and port:
https://github.com/Countly/countly-server/blob/master/frontend/express/public/javascripts/countly/countly.config.sample.js#L10

only in your case modify countly.config.js and not countly.config.sample.js

**Comment by mayulu** [comment]
@ar2rsawseen Thank you.  It is the definite solution.
