### ISSUE TITLE
MongoDB driver could not handle connection string correctly

### ISSUE THREAD

**Issue by jeffguorg** [Countly/countly-server#465]
### Expected Behavior

countly-server could connect to a hosted mongodb instance

### Current Behavior

failed when parsing connection string. 

### Screenshots (if appropriate):

it prompted
```
/home/ubuntu/countly/node_modules/mongodb/lib/url_parser.js:92                                            
      throw new Error('double colon in host identifier');                                                 
      ^                                              

Error: double colon in host identifier               
    at module.exports (/home/ubuntu/countly/node_modules/mongodb/lib/url_parser.js:92:13)                 
    at connect (/home/ubuntu/countly/node_modules/mongodb/lib/mongo_client.js:482:16)                     
    at Function.MongoClient.connect (/home/ubuntu/countly/node_modules/mongodb/lib/mongo_client.js:246:3) 
    at SkinClass.SkinDb._open (/home/ubuntu/countly/node_modules/mongoskin/lib/db.js:35:25)               
    at SkinClass.open (/home/ubuntu/countly/node_modules/mongoskin/lib/utils.js:127:14)                   
    at SkinClass.(anonymous function) [as on] (/home/ubuntu/countly/node_modules/mongoskin/lib/utils.js:83:14)                                                                                                       
    at pluginManager.dbConnection (/home/ubuntu/countly/plugins/pluginManager.js:688:19)                  
    at pluginManager.singleDefaultConnection (/home/ubuntu/countly/plugins/pluginManager.js:543:21)       
    at new Manager (/home/ubuntu/countly/api/parts/jobs/manager.js:30:21)                                 
    at Object.<anonymous> (/home/ubuntu/countly/api/parts/jobs/manager.js:430:21)                         
    at Module._compile (module.js:577:32)            
    at Object.Module._extensions..js (module.js:586:10)                                                   
    at Module.load (module.js:494:32)                
    at tryModuleLoad (module.js:453:12)              
    at Function.Module._load (module.js:445:3)       
    at Module.require (module.js:504:17)  
```

### Possible Solution

stepped into the code and found:
1. api/api.js and frontend/express/app.js use pluginManager to create db connection, which always uses frontend's config(frontend/express/config.js)
2. pluginManager has a method called singleDefaultConnection. it can handle only db config  in dict form, but not handle connection string. so your comment in config.sample.js is really misleading. it says you can use three forms of db config.

both problem are tolerable but easy be fixed. at lease you can refer in the api/config.sample.js that admin should config db in frontend/express/config.js or vice versa. 

### Steps to Reproduce (for bugs)

1. install countly server
2. modify config.js: replace mongodb config in {api,frontend/express}/config.js with ```mongodb: "mongodb://countly:Ki8cbn6VLmb9sAe2@10.0.0.15:27017/countly?authSource=admin",```
3. restart countly server
4. api server failed to start

### Context

The issue occured when i was setting up a countly server on my VPS

### Your Environment

* Operating System and version:
* Any changes you have made to your instance: 
ubuntu 16.04.01
modified the mongodb config only

it takes a day of me and a friend. wish i could help with these information

**Comment by ar2rsawseen** [comment]
Fixed here:
https://github.com/Countly/countly-server/commit/c823104aa0ebb64888bad46dc44ae87d20697d44

**Comment by ar2rsawseen** [comment]
This is now released in https://github.com/Countly/countly-server/releases/tag/v18.04
