### ISSUE TITLE
docker compose；no connect Mongodb；ERROR：2024-11-19T02:20:17.982Z: INFO [jobs:manager] Cancelling 0 jobs { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]

### ISSUE THREAD

**Issue by xiebin1998** [Countly/countly-server#5777]
2024-11-19T02:20:17.982Z: INFO [jobs:manager] Cancelling 0 jobs { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] at Pool.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:431:11) at emitOne (events.js:116:13) at Pool.emit (events.js:211:7) at connect (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:557:14) at makeConnection (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connect.js:39:11) at callback (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connect.js:261:5) at Socket.err (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connect.js:286:7) at Object.onceWrapper (events.js:315:30) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at emitErrorNT (internal/streams/destroy.js:66:8) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickCallback (internal/process/next_tick.js:181:9) name: 'MongoNetworkError', errorLabels: [ 'TransientTransactionError' ], [Symbol(mongoErrorContextSymbol)]: {} } { MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] at Pool.<anonymous> (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:431:11) at emitOne (events.js:116:13) at Pool.emit (events.js:211:7) at connect (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/pool.js:557:14) at makeConnection (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connect.js:39:11) at callback (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connect.js:261:5) at Socket.err (/opt/countly/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connect.js:286:7) at Object.onceWrapper (events.js:315:30) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at emitErrorNT (internal/streams/destroy.js:66:8) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickCallback (internal/process/next_tick.js:181:9) name: 'MongoNetworkError', errorLabels: [ 'TransientTransactionError' ],

This is a problem，i do not handle it

**Comment by wen495713** [comment]
i got the same problem after i remove the line `- NODE_OPTIONS="--max-old-space-size=2048"` from docker-compose.yml,
the logs also contains some error about `Error: Cannot find module './xxx/xxx'`

is that anyone come and check my post?
https://discord.com/channels/1088398296789299280/1352823550435917844/1352823550435917844
