### ISSUE TITLE
Sudden database connections leak and hang

### ISSUE THREAD

**Issue by andreialecu** [Countly/countly-server#850]
### Expected Behavior

Number of database connections should be stable and countly shouldn't hang.

### Current Behavior

Been running countly server for about 10 days of uptime on an EC2 volume, with an external mongo hosted in the MongoDB Atlas cloud.

Got alerted by MongoDB Atlas that the number of connections is approaching the plan limit. The connections were held for several hours until rebooting the EC2 VM that is hosting countly. During this time, countly was apparently inaccessible. I tried the dashboard after identifiying the error and it wouldn't respond, timing out eventually.

CPU usage was low on the VM (2-5%) while this condition occured.

### Screenshots (if appropriate):

Here's a screenshot from Atlas showing the sudden connection increase:

![image](https://user-images.githubusercontent.com/697707/53533712-8f347b00-3b04-11e9-8bf4-ba623907e4fc.png)

### More Description

At the exact same time the # of connections exploded on that graph, these were logged in the server log.

```
2019-02-27T20:52:54.882Z: INFO	[jobs:handle]	Starting job handle in 3405
2019-02-27T20:52:54.916Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nl","did":"363DAD70-7F91-4C53-9053-195AEAE02924"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nl","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nl","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}
2019-02-27T20:52:54.935Z: INFO	[jobs:scanner]	Checking plugins ["mobile","web","desktop","plugins","density","locale","browser","sources","views","enterpriseinfo","systemlogs","errorlogs","reports","crashes","push","star-rating","slipping-away-users","compare","server-stats","dbviewer","assistant","plugin-upload","times-of-day","compliance-hub","video-intelligence-monetization","alerts","onboarding","EChartMap","system-utility"]
2019-02-27T20:52:55.015Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nm","did":"363DAD70-7F91-4C53-9053-195AEAE02924"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nm","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nm","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}
2019-02-27T20:52:55.089Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nn","did":"363DAD70-7F91-4C53-9053-195AEAE02924"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nn","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Nn","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}
2019-02-27T20:52:55.206Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"No","did":"363DAD70-7F91-4C53-9053-195AEAE02924"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"No","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"No","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}
2019-02-27T20:52:55.437Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Np","did":"363DAD70-7F91-4C53-9053-195AEAE02924"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Np","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a\" }","op":{"_id":"cfb3832c6121e08e03d8ba7a781ac3ebe7621f6a","uid":"Np","did":"363DAD70-7F91-4C53-9053-195AEAE02924"}}
2019-02-27T20:52:58.629Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nr","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nr","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nr","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:58.796Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Ns","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Ns","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Ns","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:58.945Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nt","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nt","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nt","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.092Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nu","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nu","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nu","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.169Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nv","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nv","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nv","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.337Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nw","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nw","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nw","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.446Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nx","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nx","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nx","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.619Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Ny","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Ny","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Ny","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.644Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nz","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nz","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"Nz","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.672Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"NA","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"NA","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"NA","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
2019-02-27T20:52:59.865Z: ERROR	[db:write]	Error writing app_users5c5b17b261a8ce664ae55c6d {"name":"insert","args":[{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"NB","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"},null]} WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"NB","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}) {"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: countly.app_users5c5b17b261a8ce664ae55c6d index: _id_ dup key: { : \"751903064360f4916599d57568fbf4019ae95d61\" }","op":{"_id":"751903064360f4916599d57568fbf4019ae95d61","uid":"NB","did":"17F8D170-892D-4E1E-83C3-82F9E2EEDCC7"}}
```

### Your Environment

Amazon EC2 Ubuntu t3.micro instance in VPC
External MongoDB on MongoDB Atlas in same VPC
Countly Community Edition v18.08.2

**Comment by ar2rsawseen** [comment]
So MongoDB driver behavior is, lazy connection pool
It opens up how many connections required, opens new ones only when all existing ones are busy and keeps them open forever.

Countly uses multiple different pool sizes. Firstly because there are multiple forked processes
Secondly there are slower and faster operations, so slower ones won't slow down fast ones.
Etc

With default pool size settings:
For single core server it is normal to experience up to 1552 connections
For 4 core server is is normal to have up to 6055 connections
Pool size calculator: https://code.count.ly/helpers.html

If your server receives steady traffic, usually connection pool size does not go up to the max.
The fact that you have those errors in the logs, means there were many concurrent requests to your server, which increase connection pool size, if there are no open connections to handle operation.

If database fails to provide that opened connection, well then driver may go nuts and you get the stuck server as result.

So all in all, I say this is all expected and how it is intended to be by the connection driver and our implementation of it.

Just configure your settings in frontend (https://github.com/Countly/countly-server/blob/master/frontend/express/config.sample.js#L26) and api (https://github.com/Countly/countly-server/blob/master/api/config.sample.js#L26) for lower connection pool size, that does not exceed your Atlas limit (using pool size calculator) and you will be fine. 

Unless your traffic is big, then the queries will get queued and server will probably run out of memory, because of smaller connection pool size not letting through enough data

**Comment by andreialecu** [comment]
My mongodb is set via a connection string, but there is no poolsize defined in the string.

https://docs.mongodb.com/manual/reference/connection-string/

According to the link above, the default pool size is 100, but there were over almost 200 connections leaked instantaneously. This is a single server installation.

Based on other application logs, there was no sudden traffic burst at that time. The whole countly installation never sees more than maximum 50-100 simultaneous users. Data Points is shown at ~500k over 1 month of usage and the traffic is pretty consistent.

Should connections not be released at some point? Is there a watchdog that could restart countly if this happens?

**Comment by ar2rsawseen** [comment]
Even with connection string I think you should be able to provide pool settings:
https://docs.mongodb.com/manual/reference/connection-string/#urioption.maxPoolSize

Just make sure to provide less for frontend and more for api ones.

And as far as I know, connections are not released by driver. There may be OS level settings for keepalive that gets them closed eventually.

If there was no traffic, maybe there it was some scheduled job, or something like that.

But in overall, point is, that Countly is not a blog or a website, it is analytics tool designed to have ability of high data throughoutput and thus has aggressive default settings and kind of counts with having such resources.

Limiting would be the best way to ensure it works properly, but again up to some point of traffic. If you see resources like memory or CPU are started to get used more and more, it is possible db querues are being queued on server, because all connections are too busy, because there are not many of them available.

**Comment by andreialecu** [comment]
Alright, according to: https://github.com/Countly/countly-server/blob/master/plugins/pluginManager.js#L976-L1011 there's some custom logic to read the pool size out of the connection string.

It does look like the API was working during the time where this incident occurred, because I see activity during the time in the dashboard now.

It's possible that just the dashboard was stuck.

**Comment by ar2rsawseen** [comment]
I don't really think so.

Dashboard itself does not have any load, unless you actually login and view anything. While API has the constant load of incoming data. The only thing they share is database server.

That is why, when you say dashboard was not loading, my first assumption is, database cannot respond to dashboard queries. Which means database is down, or connection poolsize is overloaded and db server cannot provide more opened connections, etc.

To my knowledge we have not yet experienced dashboard process being stuck that way separately. We had problems with API processes on NodeJS 6 with process being stuck, but this has been solved when moving to NodeJS 8+

So in my experience, unless Countly process is not stopped itself, dashboard not loading always has to do something with database not responding.

**Comment by andreialecu** [comment]
One thing to note is that the Atlas connection limit was NOT actually hit. So any problems wouldn't have been because of that. It was at ~80% of the plan size. It's just what alerted me of the problem.

The dashboard log only has this in it:

```
            at /root/countly/plugins/web/frontend/app.js:25:17
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/countly/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/countly/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:95:5)
    at /root/countly/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/countly/node_modules/express/lib/router/index.js:335:12)
    at next (/root/countly/node_modules/express/lib/router/index.js:275:10)
    at prevent.defaultPrevent (/root/countly/frontend/express/libs/preventBruteforce.js:51:9)
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/countly/node_modules/express/lib/router/index.js:317:13)
    at /root/countly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/countly/node_modules/express/lib/router/index.js:335:12)
    at next (/root/countly/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/root/countly/node_modules/express/lib/router/index.js:317:13)
```

It's not timestamped so I'm not sure if it's from the same incident.

**Comment by ar2rsawseen** [comment]
I think it is missing the start of the stack trace? Which usually indicates error?

**Comment by andreialecu** [comment]
Ah, indeed. It's how I see it in the dashboard here:

![image](https://user-images.githubusercontent.com/697707/53567025-9d1ae800-3b66-11e9-9357-85b9bdc61850.png)

But I clicked download and it looks like this:

```
ReferenceError: request is not defined
    at /root/countly/plugins/web/frontend/app.js:25:17
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/countly/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/countly/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:95:5)
    at /root/countly/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/root/countly/node_modules/express/lib/router/index.js:335:12)
    at next (/root/countly/node_modules/express/lib/router/index.js:275:10)
    at prevent.defaultPrevent (/root/countly/frontend/express/libs/preventBruteforce.js:51:9)
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/countly/node_modules/express/lib/router/index.js:317:13)
    at /root/countly/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/countly/node_modules/express/lib/router/index.js:335:12)
    at next (/root/countly/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/root/countly/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/root/countly/node_modules/express/lib/router/index.js:317:13)
```

**Comment by ar2rsawseen** [comment]
Which Countly version are you using? I think that has been fixed a while ago. Latest version is 19.02.1

And yes, this seems to be an error that would crash the process. But supervisor would just restart the process automatically in this case. So I think this would not have caused any problem.

Unless of course some specific request comes it (which is possible for tracking pixel.png)
and it crashes the process, supervisor restarts it and SDK retries request again and again crashing the process again and again.
Then I guess you could have experienced that dashboard is not accessible, but API still working.

But in this case, I think, restarting process would not have helped at all

**Comment by andreialecu** [comment]
I was on 18.08.2, I just upgraded now and will monitor. Thanks.

**Comment by andreialecu** [comment]
I just had the same thing happen on 19.02.1

Incident occured here:

![image](https://user-images.githubusercontent.com/697707/54201967-a6497480-44d7-11e9-898d-716cb5f9bdff.png)

Countly dashboard completely unresponsive. I had a health check set up to: https://mydomain:443/o/ping and it triggered, so api was down too. Rebooted VM to get it back up.

This time there is nothing relevant in the server log at all.

I'm pretty sure the burst of connections is just a symptom of some sort of race condition or other problem, not the main cause why it locks up. There was no unusual traffic burst in the app at that point. It was actually quite low on traffic.

**Comment by andreialecu** [comment]
Some further information actually. 

I have checked the timestamp on the VM launch time after the reboot and it was 20:25 local time. So exactly the same as the spike on the graph above. This means that the connection spike was generated by the restart, probably because of a burst of requests coming from the clients, which were cached during the downtime.

The only other relevant thing I can find during the outage is this CPU usage spike:
![image](https://user-images.githubusercontent.com/697707/54207916-b8311480-44e3-11e9-8fc1-ddfc9ffa6bea.png)

It started occuring at or around 17:10 UTC (19:10 local, so 1 hour before the connection graph showing the spike). I have received a notification from AWS CloudWatch with Timestamp: Monday 11 March, 2019 17:25:45 UTC. I have managed to reboot it about 1 hour later, CPU usage cleared up after that, as expected.

**Comment by andreialecu** [comment]
Also, network_in graph for the instance:

![image](https://user-images.githubusercontent.com/697707/54208632-f11db900-44e4-11e9-9e6c-5c8c13fdb3a9.png)

**Comment by andreialecu** [comment]
I have moved to docker containers on AWS ECS for hosting countly. Running on its own instance was very unstable with hard lockups every few days.

At least with docker, health checks can step in and restart things.

Going to close this for now.
