### ISSUE TITLE
countly failed to start after upgrade

### ISSUE THREAD

**Issue by nimogit** [Countly/countly-server#902]
countly failed to start after upgrading from 18.01 (followed all the upgrade in order) to 19.02

service is started as shown by countly status:
countly-supervisor start/running, process 13286

i'm on ubuntu 14.04
countly-api.log
<pre>
/home/countly/web/countly/api/parts/jobs/manager.js:128
                    let promise = toCancel && toCancel.length ? sequence(toCancel, async j => {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/countly/web/countly/api/parts/jobs/index.js:4:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
/home/countly/web/countly/api/parts/jobs/manager.js:128
                    let promise = toCancel && toCancel.length ? sequence(toCancel, async j => {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/countly/web/countly/api/parts/jobs/index.js:4:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
/home/countly/web/countly/api/parts/jobs/manager.js:128
                    let promise = toCancel && toCancel.length ? sequence(toCancel, async j => {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/countly/web/countly/api/parts/jobs/index.js:4:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
/home/countly/web/countly/api/parts/jobs/manager.js:128
                    let promise = toCancel && toCancel.length ? sequence(toCancel, async j => {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/countly/web/countly/api/parts/jobs/index.js:4:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
</pre>

countly-dashboard.log
<pre>
/home/countly/web/countly/frontend/express/app.js:1623
            countlyDb.collection('members').findOne({username: req.body.username}, async function(err2, user) {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
/home/countly/web/countly/frontend/express/app.js:1623
            countlyDb.collection('members').findOne({username: req.body.username}, async function(err2, user) {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
/home/countly/web/countly/frontend/express/app.js:1623
            countlyDb.collection('members').findOne({username: req.body.username}, async function(err2, user) {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
/home/countly/web/countly/frontend/express/app.js:1623
            countlyDb.collection('members').findOne({username: req.body.username}, async function(err2, user) {
                                                                                   ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
</pre>

**Comment by ar2rsawseen** [comment]
Hello, 
it looks like you still have old nodejs version
This script should have upgraded your NodeJS version to 8+
https://github.com/Countly/countly-server/blob/master/bin/upgrade/18.08/upgrade.sh#L19

**Comment by nimogit** [comment]
As i mentioned before i did go through all the upgrade steps, so i did run the 18.08 upgrade shell
But you are absolutely right, it was indeed the node version problem with async package.
Apparently i had 2 different version of nodes  installed

"node -v" returned 6.2.2
while "nodejs -v" returned 8.16.0
"which node" resolved to /usr/local/bin/node
while "which nodejs" resolved to /usr/bin/nodejs

so i did the following:
rm -rf /usr/local/bin/node*
rm -rf /usr/local/include/node*
ln -s 'which nodejs' 'which node'

the i did re-run the upgrade again and that fixed the issue for me
